name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Protocol Buffers Compiler
      run: |
        sudo apt-get update
        sudo apt-get install -y protobuf-compiler

    - name: Run cargo fmt (check mode)
      run: cargo fmt --all -- --check

    - name: Run cargo clippy (warnings as errors)
      run: cargo clippy --quiet --all-targets --all-features -- -D warnings

    - name: Build
      run: cargo build --quiet

    - name: Run tests
      run: cargo test --quiet
